# Generated by Django 3.1.1 on 2020-09-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('imagen', models.CharField(max_length=256)),
                ('titulo', models.CharField(max_length=256)),
                ('cuerpo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('apellido', models.CharField(max_length=64, unique=True)),
                ('nacimiento', models.DateField()),
                ('domicilio', models.CharField(max_length=256)),
                ('grupoSanguineo', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=128)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
