# Generated by Django 3.1.1 on 2020-09-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0003_auto_20200913_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=256)),
                ('dni', models.IntegerField()),
                ('email', models.EmailField(max_length=128)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
