# Generated by Django 3.1.1 on 2020-09-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0004_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='localidad',
            field=models.CharField(default='Resistencia', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='0', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='grupoSanguineo',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
