# Generated by Django 3.1.1 on 2020-09-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0005_auto_20200915_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
