# Generated by Django 3.1.1 on 2020-09-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0006_auto_20200915_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
    ]
