# Generated by Django 3.1.1 on 2020-09-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0007_auto_20200916_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('nacimiento', models.DateField()),
                ('especialidad', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='fk_persona_dni',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Datos.persona'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='fk_medico_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Datos.medico'),
        ),
    ]
