# Generated by Django 3.1.1 on 2020-09-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0008_auto_20200920_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('fk_persona_dni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Datos.persona')),
                ('grupoSanguineo', models.CharField(max_length=4, null=True)),
                ('fuma', models.CharField(max_length=16)),
                ('bebe', models.CharField(max_length=16)),
                ('alergias', models.CharField(max_length=512)),
                ('medicamentos', models.CharField(max_length=512)),
                ('enfcronica', models.CharField(max_length=512)),
                ('antquirurgicos', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='grupoSanguineo',
        ),
    ]
