# Generated by Django 3.1.1 on 2020-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0009_auto_20200922_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fk_medico_id',
        ),
        migrations.AddField(
            model_name='turno',
            name='especialista',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='nombrePago',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='pago',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
